create table t(id int, name char, price float);
insert into t values (1,'ali',1.111);
insert into t values (2,'bob',2.222);
insert into t values (3,'cin',3.333);
insert into t values (4,'def',4.444);
select * from t;
select count(*) from t;
select count(1) from t;
select count(id) from t;
select min(id) from t;
select min(name) from t;
select max(id) from t;
select max(name) from t;
select avg(id) from t;
select avg(price) from t;
select avg(price), max(id), min(name) from t;
select count(*,id) from t;
select count() from t;
select count(not_exists_col) from t;
drop table t;