drop table pr1;
drop table pr2;
drop table pr3;
create table pr1(id int, age int);
create table pr2(id int, age int);
create table pr3(id int, age int);
insert into pr1 values (1, 7);
insert into pr1 values (2, 8);
insert into pr2 values (2, 7);
insert into pr2 values (2, 5);
insert into pr2 values (3, 7);
insert into pr3 values (3, 1);
insert into pr3 values (4, 2);
select * from pr1,pr2;
select * from pr1,pr2 where pr1.id=pr2.id;
select * from pr1,pr2 where pr1.id=pr2.id and pr2.age > 6;
select pr1.id,pr2.age from pr1,pr2;
-- select pr1.id,pr2.age,pr1.age from pr1,pr2;
select * from pr1,pr2,pr3;