name: MiniOB流水线
on: push

jobs:
  print:
    name: Runner Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print Directory
        run: |
          ls
          pwd
          uname -a
          gcc -v

  build:
    name: Build miniOB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build ENV
        run: |
          git submodule update --init --recursive
          mkdir build && cd build
          cmake ..
          make -j
      - name: Run Tests
        continue-on-error: true
        run: |
          cd build/unitest
          ctest
      - name: Upload Test Artifact
        uses: actions/upload-artifact@v2
        with:
          name: test_log
          path: Testing/Temporary/LastTest.log
