name: MiniOB Pipeline
on: push

jobs:
  miniob:
    name: MiniOB Job
    runs-on: ubuntu-latest
    steps:
      - name: Install GCC
        run: |
          sudo apt install gcc-8 g++-8
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        env:
          CC: gcc-8
          CXX: g++-8
        run: |
          cmake -S . -B build
          cmake --build build -j
      - name: Run Tests
        run: |
          ctest --test-dir build/unitest --repeat until-fail:10
      - name: Upload Test Artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test_log
          path: build/unitest/Testing/Temporary/LastTest.log
