name: CI
on: push

jobs:
  build_and_test:
    name: CI-${{ matrix.build_type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [ DEBUG, RELEASE ]
    steps:
      - name: Install Tools
        run: |
          sudo apt install gcc-8 g++-8 valgrind
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        env:
          CC: gcc-8
          CXX: g++-8
        run: |
          cmake -D${{ matrix.build_type }}=1 -S . -B build
          cmake --build build -j
      - name: Run Tests
        run: |
          ctest -T memcheck --test-dir build/unitest --repeat until-fail:10
      - name: Upload Test Artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test_log
          path: build/unitest/Testing/Temporary/*
