name: MiniOB流水线
on: push

jobs:
  print:
    name: Runner Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Print a greeting
      #   env:
      #     MY_VAR: Hi there! My name is
      #     FIRST_NAME: Mona
      #     MIDDLE_NAME: The
      #     LAST_NAME: Octocat
      #   run: |
      #     echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
      - name: Print Directory
        run: |
          ls
          pwd
          uname -a
          gcc -v

  build:
    name: Build miniOB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build ENV
        run: |
          git submodule update --init --recursive
          mkdir build && cd build
          cmake ..
          make -j
      - name: Test SQL
        run: |
          cd build
          ctest
      - name: GoogleTest
        run: |
          ./build/bin/bitmap_test  --gtest_output=xml:bitmap_test.xml || true
          ./build/bin/bp_manager_test  --gtest_output=xml:bp_manager_test.xml || true
      - name: Generate Test Report
        run: |
          git clone https://github.com/IcyLeaves/gtest-report-prettify.git
          cd gtest-report-prettify
          python -m gtest_parser ../bitmap_test.xml bitmap_test.html
          python -m gtest_parser ../bp_manager_test.xml bp_manager_test.html
      - name: Upload Test Artifact
        uses: actions/upload-artifact@v2
        with:
          name: gtest_reports
          path: gtest-report-prettify
